Pb compile e2fsprogs

diff --git a/build/ports/e2fsprogs/Makefile b/build/ports/e2fsprogs/Makefile
--- a/build/ports/e2fsprogs/Makefile
+++ b/build/ports/e2fsprogs/Makefile
@@ -36,11 +36,11 @@ post-patch:
 # don't build/install libext2fs.info
 	@${REINPLACE_CMD} -e 's/ install-doc-libs$$//' ${WRKSRC}/Makefile.in
 	@${REINPLACE_CMD} -E -e 's/md5sum ([^ ]*)/printf "%s  %s\\n" $$(md5 -q \1) \1/' \
-	    -e "s/ == 0/ = 0/" ${WRKSRC}/tests/[a-t]_*/script
+		-e "s/ == 0/ = 0/" ${WRKSRC}/tests/[a-t]_*/script
 # disable f_mmp_garbage, fails on FreeBSD, and the resize*big_expand tests,
 # which are too unwieldy to run automatically (need too much free space).
 # f_extent_oobounds fails in Tinderbox and is fine outside, reason unclear.
-.for i in f_mmp_garbage f_extent_oobounds r_64bit_big_expand r_bigalloc_big_expand r_ext4_big_expand 
+.for i in f_mmp_garbage f_extent_oobounds r_64bit_big_expand r_bigalloc_big_expand r_ext4_big_expand
 	@${MV} ${WRKSRC}/tests/${i} ${WRKSRC}/tests/disabled_test-${i}
 .endfor
 
@@ -59,12 +59,12 @@ post-build:
 # check that e2fsck isn't dynalinked against anything but libc.so:
 	@${ECHO_CMD} -n "===>  checking that e2fsck depends on no shared objects beyond libc.so: "
 	@a="$$(ldd ${WRKSRC}/e2fsck/e2fsck 2>/dev/null \
-	    | ${GREP} -v 'not a dynamic executable' \
-	    | ${GREP} '=>' \
-	    | ${AWK}  '{print $$3;}' \
-	    | ${GREP} -v '^/lib/libc\.so\.' || :)"; \
+		| ${GREP} -v 'not a dynamic executable' \
+		| ${GREP} '=>' \
+		| ${AWK}  '{print $$3;}' \
+		| ${GREP} -v '^/lib/libc\.so\.' || :)"; \
 	if test "x$$a" = "x" ; then echo 'PASS' ; else \
-	    echo 'FAIL' ; echo '===>  e2fsck depends on:' ; echo "$$a" ; exit 1 ; fi
+		echo 'FAIL' ; echo '===>  e2fsck depends on:' ; echo "$$a" ; exit 1 ; fi
 # Build fsck(8) wrapper
 	${CC} ${CPPFLAGS} ${CFLAGS} ${LDFLAGS} -s ${LIBS} \
 		-o ${WRKSRC}/fsck_ext2fs ${FILESDIR}/fsck_ext2fs.c
