Update e2fsprogs

diff --git a/build/ports/e2fsprogs/Makefile b/build/ports/e2fsprogs/Makefile
--- a/build/ports/e2fsprogs/Makefile
+++ b/build/ports/e2fsprogs/Makefile
@@ -1,5 +1,5 @@
 PORTNAME=		e2fsprogs
-PORTVERSION=	1.42.9
+PORTVERSION=	1.42.10
 PORTREVISION?= 0
 CATEGORIES=		sysutils
 COMMENT=		Utilities & library to manipulate ext2/3/4 filesystems
@@ -10,41 +10,43 @@ MASTER_SITES=		KERNEL_ORG/linux/kernel/people/tytso/${PORTNAME}/v${PORTVERSION}
 
 PATCH_STRIP=	  -p1
 NO_STAGE=       yes
-USE_GMAKE=	  yes
+USES=           gmake pkgconfig tar:xz
 USE_CSTD=	  gnu99
 USE_LDCONFIG=	  yes
-USE_XZ=         yes
 GNU_CONFIGURE=  yes
 MAKE_JOBS_SAFE= yes
 CONFIGURE_ARGS+=	--disable-fsck --disable-e2initrd-helper \
-									--with-root-prefix='${PREFIX}'
+					--enable-quota \
+					--with-root-prefix='${PREFIX}'
 #CONFIGURE_ENV+=        CPPFLAGS='${CPPFLAGS} -I${WRKSRC}/lib \ 
    #               -I${LOCALBASE}/include -D_EXT2_USE_C_VERSIONS_' 
 
 CONFIGURE_ENV+=		CPPFLAGS='${CPPFLAGS} -I${WRKSRC}/lib \
 									-I${LOCALBASE}/include'
-MAKE_ARGS+=				LDFLAGS='${LDFLAGS} -L${LOCALBASE}/lib'
+MAKE_ARGS+=     LDFLAGS='${LDFLAGS} -L${LOCALBASE}/lib' pkgconfigdir='${PREFIX}/libdata/pkgconfig'
 
 .include <bsd.port.pre.mk>
 
 USE_GETTEXT=	yes
 
-post-patch:
-	@${REINPLACE_CMD} -E -e \
-		's:\$$\(libdir\)/pkgconfig:${PREFIX}/libdata/pkgconfig:' \
-		${WRKSRC}/lib/*/Makefile.in
+post-patch::
 # don't build/install libext2fs.info
 	@${REINPLACE_CMD} -e 's/ install-doc-libs$$//' ${WRKSRC}/Makefile.in
 	@${REINPLACE_CMD} -E -e 's/md5sum ([^ ]*)/printf "%s  %s\\n" $$(md5 -q \1) \1/' \
-		-e "s/ == 0/ = 0/" ${WRKSRC}/tests/[a-t]_*/script
+	    -e "s/ == 0/ = 0/" ${WRKSRC}/tests/[a-t]_*/script
 # disable f_mmp_garbage, fails on FreeBSD, and the resize*big_expand tests,
 # which are too unwieldy to run automatically (need too much free space).
 # f_extent_oobounds fails in Tinderbox and is fine outside, reason unclear.
-.for i in f_mmp_garbage f_extent_oobounds r_64bit_big_expand r_bigalloc_big_expand r_ext4_big_expand
+.for i in f_mmp_garbage m_bigjournal r_64bit_big_expand r_bigalloc_big_expand r_ext4_big_expand
 	@${MV} ${WRKSRC}/tests/${i} ${WRKSRC}/tests/disabled_test-${i}
 .endfor
 
 .if ${MASTERDIR} == ${.CURDIR}
+pre-build:
+	# fix up Makefile ordering for parallel builds
+	cd ${WRKSRC}/lib/et && ${DO_MAKE_BUILD} compile_et
+	cd ${WRKSRC}/e2fsck && ${DO_MAKE_BUILD} prof_err.h
+
 post-build:
 # Relink e2fsck statically - We need to make sure that tools for the root file
 # system are statically linked against anything that is outside the root fs,
@@ -59,12 +61,12 @@ post-build:
 # check that e2fsck isn't dynalinked against anything but libc.so:
 	@${ECHO_CMD} -n "===>  checking that e2fsck depends on no shared objects beyond libc.so: "
 	@a="$$(ldd ${WRKSRC}/e2fsck/e2fsck 2>/dev/null \
-		| ${GREP} -v 'not a dynamic executable' \
-		| ${GREP} '=>' \
-		| ${AWK}  '{print $$3;}' \
-		| ${GREP} -v '^/lib/libc\.so\.' || :)"; \
+	    | ${GREP} -v 'not a dynamic executable' \
+	    | ${GREP} '=>' \
+	    | ${AWK}  '{print $$3;}' \
+	    | ${GREP} -v '^/lib/libc\.so\.' || :)"; \
 	if test "x$$a" = "x" ; then echo 'PASS' ; else \
-		echo 'FAIL' ; echo '===>  e2fsck depends on:' ; echo "$$a" ; exit 1 ; fi
+	    echo 'FAIL' ; echo '===>  e2fsck depends on:' ; echo "$$a" ; exit 1 ; fi
 # Build fsck(8) wrapper
 	${CC} ${CPPFLAGS} ${CFLAGS} ${LDFLAGS} -s ${LIBS} \
 		-o ${WRKSRC}/fsck_ext2fs ${FILESDIR}/fsck_ext2fs.c
